services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    command: ["npm", "run", "build"]
    volumes:
      - frontend-build:/app/dist

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask-backend
    ports:
      - "7000:7000"
    volumes:
      - frontend-build:/app/static
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
      - ./backend:/app
    depends_on:
      - frontend  # default depends on frontend

volumes:
  frontend-build:
