services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    command: ["npm", "run", "build"]
    volumes:
      - frontend-build:/app/dist

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask-backend
    ports:
      - "7000:7000"
    volumes:
      - frontend-build:/app/static  # Mount the built frontend into Flask
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
      - ./backend:/app  # for development
    environment:
      - MONGO_URI=mongodb://mongo:27017/cannavaro_db
    depends_on:
      - mongo
      - frontend

  mongo:
    image: mongo:5.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  frontend-build:
