version: '3'

services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "7001:7001"
    volumes:
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro 
      - ./backend:/app  #DEVELOPMENT

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "7000:7000"
    depends_on:
      - backend
    environment:
      - VITE_API_PROXY=http://backend:7001