remote_host: host.docker.internal
remote_port: 2222
root_user: "root"
vm_password: "rootpassword"
pub_key_path: "/root/.ssh/id_rsa.pub"
gituser_name: "cannavaro_user"
local_private_key_file: "cannavaro_user_key.pem"