# 🔧 Add missing port numbers below before continuing
# Delete this file to initialize a new Cannavaro instance
services:
- name: Notes
  port: 8000
- name: PCSS
  port: 3000
- name: Pwnzer0tt1Shop
  port: 80
